package constants

import "path/filepath"

// gen
var DoNotModify = "// Autogenerated by GOAT, do not delete or modify"

// db
var (
	DBPath        = "sqlite.db"
	DBDir         = "db"
	MigrationsDir = filepath.Join("db", "migrations")
	SQLDir        = filepath.Join("db", "sql")
	SchemaDir     = filepath.Join("db", "sql", "schema")
	QueriesDir    = filepath.Join("db", "sql", "queries")
)

// assets
var (
	AssetsDir         = "assets"
	CSSDir            = filepath.Join("assets", "css")
	UserStylesDir     = filepath.Join("assets", "css", "src")
	JSDir             = filepath.Join("assets", "js")
	UserScriptsDir    = filepath.Join("assets", "js", "src")
	ImportMapFile     = filepath.Join("assets", "js", "importmap.json")
	TSConfigPahtsFile = filepath.Join("assets", "js", "tsconfig.paths.json")
)

// log
var LogDir = "logs"
